### ISSUE TITLE
web fuera de servicio 

### ISSUE THREAD

**Issue by geryescalier** [saulm/firedeptmanagement#3]
Web fuera de servicio http://bomberos.usb.ve

**Comment by saulm** [comment]
Hola Gery,

No estoy al tanto de la razón por la que el sitio está fuera de servicio, ya que me di de baja en 2013, pero supongo no tienen los recursos necesarios para mantenerla, dada la condición país.

Puedes escribirles por twitter: https://twitter.com/BomberosUSB
